import { SymbolCategory } from "./shared/messages";

/**
 * The palette contents. Each glyph is a single unicode character dropped onto
 * the canvas verbatim as a text element.
 */
export const CATEGORIES: SymbolCategory[] = [
    {
        label: "Greek (lower)",
        symbols: [
            { glyph: "α", name: "alpha" },
            { glyph: "β", name: "beta" },
            { glyph: "γ", name: "gamma" },
            { glyph: "δ", name: "delta" },
            { glyph: "ε", name: "epsilon" },
            { glyph: "ζ", name: "zeta" },
            { glyph: "η", name: "eta" },
            { glyph: "θ", name: "theta" },
            { glyph: "ι", name: "iota" },
            { glyph: "κ", name: "kappa" },
            { glyph: "λ", name: "lambda" },
            { glyph: "μ", name: "mu" },
            { glyph: "ν", name: "nu" },
            { glyph: "ξ", name: "xi" },
            { glyph: "π", name: "pi" },
            { glyph: "ρ", name: "rho" },
            { glyph: "σ", name: "sigma" },
            { glyph: "τ", name: "tau" },
            { glyph: "υ", name: "upsilon" },
            { glyph: "φ", name: "phi" },
            { glyph: "χ", name: "chi" },
            { glyph: "ψ", name: "psi" },
            { glyph: "ω", name: "omega" },
            { glyph: "ϵ", name: "epsilon (variant)" },
            { glyph: "ϑ", name: "theta (variant)" },
            { glyph: "ϕ", name: "phi (variant)" },
            { glyph: "ϱ", name: "rho (variant)" },
            { glyph: "ϖ", name: "pi (variant)" },
        ],
    },
    {
        label: "Greek (upper)",
        symbols: [
            { glyph: "Γ", name: "Gamma" },
            { glyph: "Δ", name: "Delta" },
            { glyph: "Θ", name: "Theta" },
            { glyph: "Λ", name: "Lambda" },
            { glyph: "Ξ", name: "Xi" },
            { glyph: "Π", name: "Pi" },
            { glyph: "Σ", name: "Sigma" },
            { glyph: "Φ", name: "Phi" },
            { glyph: "Ψ", name: "Psi" },
            { glyph: "Ω", name: "Omega" },
            { glyph: "ℵ", name: "aleph" },
        ],
    },
    {
        label: "Operators",
        symbols: [
            { glyph: "∑", name: "sum" },
            { glyph: "∏", name: "product" },
            { glyph: "∐", name: "coproduct" },
            { glyph: "∫", name: "integral" },
            { glyph: "∬", name: "double integral" },
            { glyph: "∭", name: "triple integral" },
            { glyph: "∮", name: "contour integral" },
            { glyph: "∂", name: "partial derivative" },
            { glyph: "∇", name: "nabla / del" },
            { glyph: "√", name: "square root" },
            { glyph: "∛", name: "cube root" },
            { glyph: "∜", name: "fourth root" },
            { glyph: "±", name: "plus-minus" },
            { glyph: "∓", name: "minus-plus" },
            { glyph: "×", name: "times" },
            { glyph: "÷", name: "divide" },
            { glyph: "⋅", name: "dot product" },
            { glyph: "∘", name: "composition" },
            { glyph: "∗", name: "asterisk operator" },
            { glyph: "⊕", name: "direct sum" },
            { glyph: "⊗", name: "tensor product" },
            { glyph: "⊙", name: "circled dot" },
        ],
    },
    {
        label: "Relations",
        symbols: [
            { glyph: "=", name: "equals" },
            { glyph: "≠", name: "not equal" },
            { glyph: "≈", name: "approximately" },
            { glyph: "≡", name: "identical to" },
            { glyph: "≅", name: "congruent" },
            { glyph: "≜", name: "defined as" },
            { glyph: "∝", name: "proportional to" },
            { glyph: "≤", name: "less or equal" },
            { glyph: "≥", name: "greater or equal" },
            { glyph: "≪", name: "much less than" },
            { glyph: "≫", name: "much greater than" },
            { glyph: "<", name: "less than" },
            { glyph: ">", name: "greater than" },
        ],
    },
    {
        label: "Sets & logic",
        symbols: [
            { glyph: "∈", name: "element of" },
            { glyph: "∉", name: "not an element of" },
            { glyph: "⊂", name: "subset" },
            { glyph: "⊆", name: "subset or equal" },
            { glyph: "⊃", name: "superset" },
            { glyph: "⊇", name: "superset or equal" },
            { glyph: "∪", name: "union" },
            { glyph: "∩", name: "intersection" },
            { glyph: "∅", name: "empty set" },
            { glyph: "∀", name: "for all" },
            { glyph: "∃", name: "there exists" },
            { glyph: "∄", name: "there does not exist" },
            { glyph: "¬", name: "not" },
            { glyph: "∧", name: "and" },
            { glyph: "∨", name: "or" },
            { glyph: "∴", name: "therefore" },
            { glyph: "∵", name: "because" },
            { glyph: "ℝ", name: "real numbers" },
            { glyph: "ℤ", name: "integers" },
            { glyph: "ℕ", name: "natural numbers" },
            { glyph: "ℚ", name: "rational numbers" },
            { glyph: "ℂ", name: "complex numbers" },
        ],
    },
    {
        label: "Arrows",
        symbols: [
            { glyph: "→", name: "right arrow" },
            { glyph: "←", name: "left arrow" },
            { glyph: "↔", name: "left-right arrow" },
            { glyph: "⇒", name: "implies" },
            { glyph: "⇐", name: "is implied by" },
            { glyph: "⇔", name: "if and only if" },
            { glyph: "↦", name: "maps to" },
            { glyph: "↑", name: "up arrow" },
            { glyph: "↓", name: "down arrow" },
            { glyph: "⟶", name: "long right arrow" },
        ],
    },
    {
        label: "Misc",
        symbols: [
            { glyph: "∞", name: "infinity" },
            { glyph: "°", name: "degree" },
            { glyph: "′", name: "prime" },
            { glyph: "″", name: "double prime" },
            { glyph: "∠", name: "angle" },
            { glyph: "⊥", name: "perpendicular" },
            { glyph: "∥", name: "parallel" },
            { glyph: "…", name: "horizontal ellipsis" },
            { glyph: "⋯", name: "midline ellipsis" },
            { glyph: "ℏ", name: "reduced Planck constant" },
            { glyph: "ℓ", name: "script l" },
            { glyph: "∎", name: "end of proof" },
        ],
    },
];
